In [1]:
# Import libraries

import pandas as pd
import numpy as np
import os

In [2]:
#path to project folder
path = '/Users/davidey/06-2023 Instacart Basket Analysis'

In [3]:
df_ords_prods_merged = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', '2023-07-28_orders_products_merged.pkl'))

In [4]:
# look at subset
df = df_ords_prods_merged[:1000000]

In [5]:
# define function for new column
def price_label(row):

  if row['prices'] <= 5:
    return 'Low-range product'
  elif (row['prices'] > 5) and (row['prices'] <= 15):
    return 'Mid-range product'
  elif row['prices'] > 15:
    return 'High range'
  else: return 'Not enough data'

In [6]:
df['price_label'] = df.apply(price_label, axis=1)

/var/folders/mr/08vwt9d53xlckqzs27_s_rz40000gn/T/ipykernel_39812/1527635097.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price_label'] = df.apply(price_label, axis=1)

In [7]:
price_label

In [8]:
df.shape

(1000000, 14)

In [9]:
df.head()

,order_id,product_id,add_to_cart_order,user_id,user_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_name,aisle_id,department_id,prices,_merge,price_label
0,2.0,33120.0,1.0,202279.0,3.0,5.0,9.0,8.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product
1,26.0,33120.0,5.0,153404.0,2.0,0.0,16.0,7.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product
2,120.0,33120.0,13.0,23750.0,11.0,6.0,8.0,10.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product
3,327.0,33120.0,5.0,58707.0,21.0,6.0,9.0,8.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product
4,390.0,33120.0,28.0,166654.0,48.0,0.0,12.0,9.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product

In [10]:
#viewing some mid-range products

In [11]:
df_merged_check = df.loc[df['price_label'].isin(['Mid-range product'])]

In [12]:
df_merged_check

,order_id,product_id,add_to_cart_order,user_id,user_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_name,aisle_id,department_id,prices,_merge,price_label
0,2.0,33120.0,1.0,202279.0,3.0,5.0,9.0,8.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product
1,26.0,33120.0,5.0,153404.0,2.0,0.0,16.0,7.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product
2,120.0,33120.0,13.0,23750.0,11.0,6.0,8.0,10.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product
3,327.0,33120.0,5.0,58707.0,21.0,6.0,9.0,8.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product
4,390.0,33120.0,28.0,166654.0,48.0,0.0,12.0,9.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,3291169.0,13176.0,8.0,26607.0,29.0,1.0,8.0,6.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product
999996,3291170.0,13176.0,1.0,158997.0,6.0,0.0,20.0,7.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product
999997,3291174.0,13176.0,4.0,106645.0,13.0,1.0,14.0,11.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product
999998,3291195.0,13176.0,3.0,57149.0,14.0,3.0,15.0,30.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product
999999,3291204.0,13176.0,7.0,146147.0,88.0,6.0,20.0,2.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product

In [13]:
df['price_label'].value_counts()

Mid-range product    983807
Low-range product     16193
Name: price_label, dtype: int64

In [14]:
df['prices'].max()

13.7

In [15]:
df.head()

,order_id,product_id,add_to_cart_order,user_id,user_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_name,aisle_id,department_id,prices,_merge,price_label
0,2.0,33120.0,1.0,202279.0,3.0,5.0,9.0,8.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product
1,26.0,33120.0,5.0,153404.0,2.0,0.0,16.0,7.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product
2,120.0,33120.0,13.0,23750.0,11.0,6.0,8.0,10.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product
3,327.0,33120.0,5.0,58707.0,21.0,6.0,9.0,8.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product
4,390.0,33120.0,28.0,166654.0,48.0,0.0,12.0,9.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product

In [16]:
df.tail()

,order_id,product_id,add_to_cart_order,user_id,user_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_name,aisle_id,department_id,prices,_merge,price_label
999995,3291169.0,13176.0,8.0,26607.0,29.0,1.0,8.0,6.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product
999996,3291170.0,13176.0,1.0,158997.0,6.0,0.0,20.0,7.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product
999997,3291174.0,13176.0,4.0,106645.0,13.0,1.0,14.0,11.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product
999998,3291195.0,13176.0,3.0,57149.0,14.0,3.0,15.0,30.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product
999999,3291204.0,13176.0,7.0,146147.0,88.0,6.0,20.0,2.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product

In [17]:
# same operation but via loc

In [18]:
df.loc[df['prices'] > 15, 'price_range_loc'] = 'High-range product'
df.loc[(df['prices'] <= 15) & (df['prices'] > 5), 'price_range_loc'] = 'Mid-range product' 
df.loc[df['prices'] <= 5, 'price_range_loc'] = 'Low-range product'

/var/folders/mr/08vwt9d53xlckqzs27_s_rz40000gn/T/ipykernel_39812/3192052085.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['prices'] > 15, 'price_range_loc'] = 'High-range product'

In [19]:
df.loc[df['prices'] > 15, 'price_range_loc'] = 'High-range product'

In [20]:
df.loc[(df['prices'] <= 15) & (df['prices'] > 5), 'price_range_loc'] = 'Mid-range product'

In [21]:
df.loc[df['prices'] <= 5, 'price_range_loc'] = 'Low-range product'

In [22]:
df['price_range_loc'].value_counts(dropna = False)

Mid-range product    983807
Low-range product     16193
Name: price_range_loc, dtype: int64

In [23]:
df['price_range_loc'].value_counts()

Mid-range product    983807
Low-range product     16193
Name: price_range_loc, dtype: int64

In [24]:
# applying loc statements to the main dataframe

In [25]:
pd.options.display.max_rows = None

In [26]:
df_ords_prods_merged['prices'].value_counts(dropna = False)

12.3       624261
10.3       510496
4.0        447272
6.3        438467
1.3        425691
7.3        411924
8.2        404015
1.4        392209
6.7        379126
4.5        367223
4.4        357026
6.8        355247
7.9        342988
14.3       334812
13.2       333183
5.7        323997
1.8        321185
9.1        320783
4.9        318220
8.8        318091
3.8        315426
6.9        314196
14.0       311640
12.8       309727
11.4       303015
3.6        300127
1.6        299352
2.0        286259
11.8       284476
5.3        284243
7.0        282884
14.7       279291
6.5        278357
8.3        276230
4.1        268269
2.9        264700
1.2        256258
8.6        254009
3.2        253782
5.2        251509
5.5        250136
3.1        249256
2.5        246421
4.2        245755
6.1        244209
1.1        242782
2.3        242051
5.8        241047
7.5        239261
14.1       238211
3.3        238041
10.5       237657
NaN        236409
7.4        233506
9.0        228576
8.4        227493
5.0        225904
13.4       225857
11.5       225399
5.1        224797
3.4        223571
7.2        223120
3.5        222786
3.7        222159
4.7        221048
8.9        219412
9.6        216626
13.5       216276
1.7        213968
11.3       212926
3.9        212805
11.2       212323
2.6        211937
5.9        208900
5.4        206769
6.4        206468
11.7       206199
2.1        206004
6.6        204936
10.6       204804
2.7        199785
9.4        197179
6.0        196985
2.4        196042
9.8        194755
4.8        193898
3.0        192650
10.7       191705
7.7        190070
14.8       188844
12.2       188444
7.8        186923
5.6        183638
11.0       183505
9.2        182444
12.1       181986
13.7       181882
6.2        178656
8.1        176806
12.6       174427
13.3       173797
13.6       172962
11.1       169709
9.9        169263
9.3        168917
14.4       168272
8.7        166742
9.5        165789
10.2       165789
10.9       165607
12.0       164718
13.8       162616
4.3        162367
12.9       160860
2.2        160243
14.9       156433
1.9        156179
1.5        154527
2.8        153979
12.5       152781
8.0        151542
11.6       148742
13.9       145234
4.6        144069
7.1        140813
14.6       139880
10.1       139263
8.5        139244
10.4       133059
14.5       129540
10.0       127842
11.9       127349
12.7       124544
9.7        120777
14.2       119314
13.1       117047
1.0        115143
13.0       114503
7.6        113878
12.4        97866
15.0        97262
10.8        89927
21.1        33805
19.6        28383
22.3        19430
24.2        15891
18.2        14923
23.2        14866
25.0        13772
23.8        12585
21.6        10598
18.7        10503
23.1         9135
23.6         8458
18.6         8451
18.1         8027
21.3         7647
15.3         7495
24.7         7283
20.7         6568
19.3         6537
24.9         5781
20.0         5775
19.7         5538
19.4         5457
20.4         5351
22.1         5204
15.9         5078
16.9         4971
23.3         4803
16.8         4795
15.7         4551
14900.0      4429
18.8         4363
24.0         4327
17.3         4309
17.1         4231
16.6         4212
16.4         3892
22.9         3884
17.0         3836
20.1         3745
23.0         3265
16.7         3105
18.5         3105
19.1         2926
24.3         2889
19.0         2823
21.7         2553
16.5         2541
15.1         2422
15.5         2325
22.6         2275
24.5         2148
23.9         2074
17.7         2073
24.6         1962
23.5         1924
16.2         1823
18.4         1762
17.4         1721
16.1         1622
23.7         1346
22.4         1280
16.0         1272
22.0         1182
22.2         1178
15.4         1175
20.6         1167
18.0         1135
22.8         1089
20.9         1075
17.2         1001
19.2          981
17.8          981
24.1          978
20.5          945
19.9          887
20.8          852
15.8          772
22.5          706
99999.0       698
21.9          689
17.6          640
21.8          546
24.4          499
15.2          494
18.9          483
19.5          453
24.8          410
17.5          369
23.4          368
19.8          344
15.6          333
16.3          287
20.3          236
17.9          137
21.4          137
20.2          123
22.7           99
21.5           85
18.3           11
21.0            8
Name: prices, dtype: int64

In [27]:
df_ords_prods_merged.describe()

,order_id,product_id,add_to_cart_order,user_id,user_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,aisle_id,department_id,prices
count,3.264245e+07,3.243625e+07,3.243624e+07,3.264245e+07,3.264245e+07,3.264245e+07,3.264245e+07,3.056424e+07,3.240605e+07,3.240605e+07,3.240605e+07
mean,1.710718e+06,2.557664e+04,8.351150e+00,1.029381e+05,1.713839e+01,2.739032e+00,1.342599e+01,1.114435e+01,7.119773e+01,9.919925e+00,1.198004e+01
std,9.873081e+05,1.409646e+04,7.126713e+00,5.946689e+04,1.752953e+01,2.090264e+00,4.246220e+00,8.806592e+00,3.821182e+01,6.281418e+00,4.956463e+02
min,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
25%,8.558860e+05,1.353500e+04,3.000000e+00,5.142200e+04,5.000000e+00,1.000000e+00,1.000000e+01,5.000000e+00,3.100000e+01,4.000000e+00,4.200000e+00
50%,1.710984e+06,2.525600e+04,6.000000e+00,1.026160e+05,1.100000e+01,3.000000e+00,1.300000e+01,8.000000e+00,8.300000e+01,9.000000e+00,7.400000e+00
75%,2.565488e+06,3.793500e+04,1.100000e+01,1.543930e+05,2.400000e+01,5.000000e+00,1.600000e+01,1.500000e+01,1.070000e+02,1.600000e+01,1.130000e+01
max,3.421083e+06,4.968800e+04,1.450000e+02,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01,1.340000e+02,2.100000e+01,9.999900e+04

In [28]:
df_ords_prods_merged.loc[(df_ords_prods_merged['prices'] <= 15) & (df_ords_prods_merged['prices'] > 5),
             'price_range_loc'] = 'Mid-range product'

In [29]:
df_ords_prods_merged.loc[df_ords_prods_merged['prices'] <= 5, 'price_range_loc'] = 'Low-range product'

In [30]:
df_ords_prods_merged.loc[df_ords_prods_merged['prices'] > 15, 'price_range_loc'] = 'High-range product'

In [31]:
df_ords_prods_merged['price_range_loc'].value_counts(dropna = False)

Mid-range product     21862005
Low-range product     10126369
High-range product      417678
NaN                     236409
Name: price_range_loc, dtype: int64

NaN I guess would be free items

In [32]:
# checking values

In [33]:
df_ords_prods_merged['orders_day_of_week'].value_counts(dropna = False)

0.0    6253163
1.0    5696950
6.0    4530449
2.0    4243329
5.0    4237104
3.0    3868914
4.0    3812541
NaN         11
Name: orders_day_of_week, dtype: int64

In [34]:
dow_nan_rows = df_ords_prods_merged[df_ords_prods_merged['orders_day_of_week'].isna()]

In [35]:
dow_nan_rows

,order_id,product_id,add_to_cart_order,user_id,user_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_name,aisle_id,department_id,prices,_merge,price_range_loc
32642450,NaN,3630.0,NaN,NaN,NaN,NaN,NaN,NaN,Protein Granola Apple Crisp,57.0,14.0,2.6,right_only,Low-range product
32642451,NaN,3718.0,NaN,NaN,NaN,NaN,NaN,NaN,Wasabi Cheddar Spreadable Cheese,21.0,16.0,12.0,right_only,Mid-range product
32642452,NaN,7045.0,NaN,NaN,NaN,NaN,NaN,NaN,Unpeeled Apricot Halves in Heavy Syrup,88.0,13.0,6.8,right_only,Mid-range product
32642453,NaN,25383.0,NaN,NaN,NaN,NaN,NaN,NaN,Chocolate Go Bites,61.0,19.0,1.8,right_only,Low-range product
32642454,NaN,27499.0,NaN,NaN,NaN,NaN,NaN,NaN,Non-Dairy Coconut Seven Layer Bar,100.0,21.0,15.0,right_only,Mid-range product
32642455,NaN,36233.0,NaN,NaN,NaN,NaN,NaN,NaN,Water With Electrolytes,100.0,21.0,10.4,right_only,Mid-range product
32642456,NaN,37703.0,NaN,NaN,NaN,NaN,NaN,NaN,Ultra Sun Blossom Liquid 90 loads Fabric Enhan...,75.0,17.0,14.3,right_only,Mid-range product
32642457,NaN,43725.0,NaN,NaN,NaN,NaN,NaN,NaN,Sweetart Jelly Beans,100.0,21.0,8.1,right_only,Mid-range product
32642458,NaN,45971.0,NaN,NaN,NaN,NaN,NaN,NaN,12 Inch Taper Candle White,101.0,17.0,9.8,right_only,Mid-range product
32642459,NaN,46625.0,NaN,NaN,NaN,NaN,NaN,NaN,Single Barrel Kentucky Straight Bourbon Whiskey,31.0,7.0,1.7,right_only,Low-range product
32642460,NaN,49540.0,NaN,NaN,NaN,NaN,NaN,NaN,Pure Squeezed Lemonade,31.0,7.0,9.1,right_only,Mid-range product

In [36]:
#It's probably best to drop these NaN rows
order_id_nan_rows = df_ords_prods_merged[df_ords_prods_merged['order_id'].isna()]

In [37]:
order_id_nan_rows

,order_id,product_id,add_to_cart_order,user_id,user_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_name,aisle_id,department_id,prices,_merge,price_range_loc
32642450,NaN,3630.0,NaN,NaN,NaN,NaN,NaN,NaN,Protein Granola Apple Crisp,57.0,14.0,2.6,right_only,Low-range product
32642451,NaN,3718.0,NaN,NaN,NaN,NaN,NaN,NaN,Wasabi Cheddar Spreadable Cheese,21.0,16.0,12.0,right_only,Mid-range product
32642452,NaN,7045.0,NaN,NaN,NaN,NaN,NaN,NaN,Unpeeled Apricot Halves in Heavy Syrup,88.0,13.0,6.8,right_only,Mid-range product
32642453,NaN,25383.0,NaN,NaN,NaN,NaN,NaN,NaN,Chocolate Go Bites,61.0,19.0,1.8,right_only,Low-range product
32642454,NaN,27499.0,NaN,NaN,NaN,NaN,NaN,NaN,Non-Dairy Coconut Seven Layer Bar,100.0,21.0,15.0,right_only,Mid-range product
32642455,NaN,36233.0,NaN,NaN,NaN,NaN,NaN,NaN,Water With Electrolytes,100.0,21.0,10.4,right_only,Mid-range product
32642456,NaN,37703.0,NaN,NaN,NaN,NaN,NaN,NaN,Ultra Sun Blossom Liquid 90 loads Fabric Enhan...,75.0,17.0,14.3,right_only,Mid-range product
32642457,NaN,43725.0,NaN,NaN,NaN,NaN,NaN,NaN,Sweetart Jelly Beans,100.0,21.0,8.1,right_only,Mid-range product
32642458,NaN,45971.0,NaN,NaN,NaN,NaN,NaN,NaN,12 Inch Taper Candle White,101.0,17.0,9.8,right_only,Mid-range product
32642459,NaN,46625.0,NaN,NaN,NaN,NaN,NaN,NaN,Single Barrel Kentucky Straight Bourbon Whiskey,31.0,7.0,1.7,right_only,Low-range product
32642460,NaN,49540.0,NaN,NaN,NaN,NaN,NaN,NaN,Pure Squeezed Lemonade,31.0,7.0,9.1,right_only,Mid-range product

In [38]:
order_id_nan_rows.shape

(11, 14)

In [39]:
df_ords_prods_merged['order_hour_of_day'].value_counts(dropna = False)

10.0    2781111
11.0    2755471
14.0    2709199
15.0    2682192
13.0    2680274
12.0    2637614
16.0    2554221
9.0     2471137
17.0    2104292
8.0     1729935
18.0    1649934
19.0    1268412
20.0     983258
7.0      897191
21.0     801073
22.0     638693
23.0     405070
6.0      292540
0.0      220354
1.0      116595
5.0       88664
2.0       69906
4.0       53639
3.0       51675
NaN          11
Name: order_hour_of_day, dtype: int64

In [40]:
#dropping on the basis of order ID, as that is the key column for the results
df_ords_prods_merged = df_ords_prods_merged.drop(df_ords_prods_merged[df_ords_prods_merged
     ['order_id'] == 'NaN'].index)

In [41]:
# checks and cleanup
df_ords_prods_merged['order_hour_of_day'].value_counts(dropna = False)

10.0    2781111
11.0    2755471
14.0    2709199
15.0    2682192
13.0    2680274
12.0    2637614
16.0    2554221
9.0     2471137
17.0    2104292
8.0     1729935
18.0    1649934
19.0    1268412
20.0     983258
7.0      897191
21.0     801073
22.0     638693
23.0     405070
6.0      292540
0.0      220354
1.0      116595
5.0       88664
2.0       69906
4.0       53639
3.0       51675
NaN          11
Name: order_hour_of_day, dtype: int64

In [42]:
df_ords_prods_merged = df_ords_prods_merged.dropna(subset=['order_id'])

In [43]:
df_ords_prods_merged['order_hour_of_day'].value_counts(dropna = False)

10.0    2781111
11.0    2755471
14.0    2709199
15.0    2682192
13.0    2680274
12.0    2637614
16.0    2554221
9.0     2471137
17.0    2104292
8.0     1729935
18.0    1649934
19.0    1268412
20.0     983258
7.0      897191
21.0     801073
22.0     638693
23.0     405070
6.0      292540
0.0      220354
1.0      116595
5.0       88664
2.0       69906
4.0       53639
3.0       51675
Name: order_hour_of_day, dtype: int64

In [44]:
#now to derive to the new column

result = []

for value in df_ords_prods_merged["orders_day_of_week"]:
    if value == 0:
        result.append("Busiest day")
    elif value == 4:
        result.append("Least busy")
    else:
        result.append("Regularly busy")

In [45]:
df_ords_prods_merged['busiest_day'] = result

In [46]:
df_ords_prods_merged['busiest_day'].value_counts(dropna = False)

Regularly busy    22576746
Busiest day        6253163
Least busy         3812541
Name: busiest_day, dtype: int64

# Task

## 2. Suppose your clients have changed their minds about the labels you created in your “busiest_day” column. Now, they want “Busiest day” to become “Busiest days” (plural). This label should correspond with the two busiest days of the week as opposed to the single busiest day. At the same time, they’d also like to know the two slowest days. Create a new column for this using a suitable method.

In [47]:
busiest_days_result = []

for value in df_ords_prods_merged["orders_day_of_week"]:
    if value == 0 or value == 1:
        busiest_days_result.append("Busiest days")
    elif value == 3 or value == 4:
        busiest_days_result.append("Slowest days")
    else:
        busiest_days_result.append("Average days")

In [48]:
busiest_days_result

['Average days',
 'Busiest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Average days',
 'Average days',
 'Slowest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Slowest days',
 'Slowest days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Average days',
 'Average days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Average days',
 'Average days',
 'Average days',
 'Slowest days',
 'Slowest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Slowest days',
 'Average days',
 'Average days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Slowest days',
 'Average days',
 'Average days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Average days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Slowest days',
 'Slowest days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Slowest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Slowest days',
 'Average days',
 'Average days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Average days',
 'Average days',
 'Slowest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Average days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Average days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Slowest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Average days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Average days',
 'Average days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Busiest days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Average days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Slowest days',
 'Slowest days',
 'Busiest days',
 'Slowest days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Average days',
 'Slowest days',
 'Average days',
 'Average days',
 'Average days',
 'Busiest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Average days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Slowest days',
 'Average days',
 'Average days',
 'Slowest days',
 'Average days',
 'Average days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Slowest days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Slowest days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Slowest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Slowest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Slowest days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Slowest days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Average days',
 'Average days',
 'Slowest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Slowest days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Average days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Average days',
 'Average days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Slowest days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Slowest days',
 'Average days',
 'Average days',
 'Busiest days',
 'Average days',
 'Average days',
 'Average days',
 'Slowest days',
 'Average days',
 'Average days',
 'Average days',
 'Slowest days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Average days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Busiest days',
 'Average days',
 'Busiest days',
 'Average days',
 'Slowest days',
 'Busiest days',
 'Average days',
 'Average days',
 ...]

# 3. Check the values of this new column for accuracy. Note any observations in markdown format.

In [49]:
df_ords_prods_merged['busiest_days'] = busiest_days_result

In [50]:
df_ords_prods_merged['busiest_days'].value_counts(dropna = False)

Average days    13010882
Busiest days    11950113
Slowest days     7681455
Name: busiest_days, dtype: int64

In [51]:
df_ords_prods_merged['orders_day_of_week'].value_counts(dropna = False)

0.0    6253163
1.0    5696950
6.0    4530449
2.0    4243329
5.0    4237104
3.0    3868914
4.0    3812541
Name: orders_day_of_week, dtype: int64

In [52]:
# busiest days check (day 0 + 1)
6253163 + 5696950

11950113

In [53]:
# looks good. Slowest days check (3 + 4)
3868914 + 3812541

7681455

In [54]:
# looks good. Average days check

In [55]:
4530449 + 4243329 + 4237104 + 11

13010893

That looks right but does include the NaN values.

In [56]:
df_ords_prods_merged.head()

,order_id,product_id,add_to_cart_order,user_id,user_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days
0,2.0,33120.0,1.0,202279.0,3.0,5.0,9.0,8.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product,Regularly busy,Average days
1,26.0,33120.0,5.0,153404.0,2.0,0.0,16.0,7.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product,Busiest day,Busiest days
2,120.0,33120.0,13.0,23750.0,11.0,6.0,8.0,10.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product,Regularly busy,Average days
3,327.0,33120.0,5.0,58707.0,21.0,6.0,9.0,8.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product,Regularly busy,Average days
4,390.0,33120.0,28.0,166654.0,48.0,0.0,12.0,9.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product,Busiest day,Busiest days

In [57]:
df_ords_prods_merged.describe()

,order_id,product_id,add_to_cart_order,user_id,user_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,aisle_id,department_id,prices
count,3.264245e+07,3.243624e+07,3.243624e+07,3.264245e+07,3.264245e+07,3.264245e+07,3.264245e+07,3.056424e+07,3.240604e+07,3.240604e+07,3.240604e+07
mean,1.710718e+06,2.557663e+04,8.351150e+00,1.029381e+05,1.713839e+01,2.739032e+00,1.342599e+01,1.114435e+01,7.119773e+01,9.919923e+00,1.198004e+01
std,9.873081e+05,1.409646e+04,7.126713e+00,5.946689e+04,1.752953e+01,2.090264e+00,4.246220e+00,8.806592e+00,3.821182e+01,6.281418e+00,4.956464e+02
min,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
25%,8.558860e+05,1.353500e+04,3.000000e+00,5.142200e+04,5.000000e+00,1.000000e+00,1.000000e+01,5.000000e+00,3.100000e+01,4.000000e+00,4.200000e+00
50%,1.710984e+06,2.525600e+04,6.000000e+00,1.026160e+05,1.100000e+01,3.000000e+00,1.300000e+01,8.000000e+00,8.300000e+01,9.000000e+00,7.400000e+00
75%,2.565488e+06,3.793500e+04,1.100000e+01,1.543930e+05,2.400000e+01,5.000000e+00,1.600000e+01,1.500000e+01,1.070000e+02,1.600000e+01,1.130000e+01
max,3.421083e+06,4.968800e+04,1.450000e+02,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01,1.340000e+02,2.100000e+01,9.999900e+04

In [58]:
#now get rid of the 'busiest_day' column, as client changed their mind about having it
df_ords_prods_merged = df_ords_prods_merged.drop(columns = ['busiest_day'])

In [59]:
df_ords_prods_merged.head()

,order_id,product_id,add_to_cart_order,user_id,user_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_days
0,2.0,33120.0,1.0,202279.0,3.0,5.0,9.0,8.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product,Average days
1,26.0,33120.0,5.0,153404.0,2.0,0.0,16.0,7.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product,Busiest days
2,120.0,33120.0,13.0,23750.0,11.0,6.0,8.0,10.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product,Average days
3,327.0,33120.0,5.0,58707.0,21.0,6.0,9.0,8.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product,Average days
4,390.0,33120.0,28.0,166654.0,48.0,0.0,12.0,9.0,Organic Egg Whites,86.0,16.0,11.3,both,Mid-range product,Busiest days

## 4. When too many users make Instacart orders at the same time, the app freezes. The senior technical officer at Instacart wants you to identify the busiest hours of the day. Rather than by hour, they want periods of time labeled “Most orders,” “Average orders,” and “Fewest orders.” Create a new column containing these labels called “busiest_period_of_day.”

In [60]:
# first see where the frequency lies
df_ords_prods_merged['order_hour_of_day'].value_counts(dropna = False)

10.0    2781111
11.0    2755471
14.0    2709199
15.0    2682192
13.0    2680274
12.0    2637614
16.0    2554221
9.0     2471137
17.0    2104292
8.0     1729935
18.0    1649934
19.0    1268412
20.0     983258
7.0      897191
21.0     801073
22.0     638693
23.0     405070
6.0      292540
0.0      220354
1.0      116595
5.0       88664
2.0       69906
4.0       53639
3.0       51675
Name: order_hour_of_day, dtype: int64

In [61]:
df_ords_prods_merged['order_hour_of_day'].value_counts(dropna = False)

10.0    2781111
11.0    2755471
14.0    2709199
15.0    2682192
13.0    2680274
12.0    2637614
16.0    2554221
9.0     2471137
17.0    2104292
8.0     1729935
18.0    1649934
19.0    1268412
20.0     983258
7.0      897191
21.0     801073
22.0     638693
23.0     405070
6.0      292540
0.0      220354
1.0      116595
5.0       88664
2.0       69906
4.0       53639
3.0       51675
Name: order_hour_of_day, dtype: int64

In [62]:
df_ords_prods_merged.describe()

,order_id,product_id,add_to_cart_order,user_id,user_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,aisle_id,department_id,prices
count,3.264245e+07,3.243624e+07,3.243624e+07,3.264245e+07,3.264245e+07,3.264245e+07,3.264245e+07,3.056424e+07,3.240604e+07,3.240604e+07,3.240604e+07
mean,1.710718e+06,2.557663e+04,8.351150e+00,1.029381e+05,1.713839e+01,2.739032e+00,1.342599e+01,1.114435e+01,7.119773e+01,9.919923e+00,1.198004e+01
std,9.873081e+05,1.409646e+04,7.126713e+00,5.946689e+04,1.752953e+01,2.090264e+00,4.246220e+00,8.806592e+00,3.821182e+01,6.281418e+00,4.956464e+02
min,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
25%,8.558860e+05,1.353500e+04,3.000000e+00,5.142200e+04,5.000000e+00,1.000000e+00,1.000000e+01,5.000000e+00,3.100000e+01,4.000000e+00,4.200000e+00
50%,1.710984e+06,2.525600e+04,6.000000e+00,1.026160e+05,1.100000e+01,3.000000e+00,1.300000e+01,8.000000e+00,8.300000e+01,9.000000e+00,7.400000e+00
75%,2.565488e+06,3.793500e+04,1.100000e+01,1.543930e+05,2.400000e+01,5.000000e+00,1.600000e+01,1.500000e+01,1.070000e+02,1.600000e+01,1.130000e+01
max,3.421083e+06,4.968800e+04,1.450000e+02,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01,1.340000e+02,2.100000e+01,9.999900e+04

In [63]:
df_ords_prods_merged.shape

(32642450, 15)

In [64]:
df_ords_prods_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32642450 entries, 0 to 32642449
Data columns (total 15 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                float64
 1   product_id              float64
 2   add_to_cart_order       float64
 3   user_id                 float64
 4   user_order_number       float64
 5   orders_day_of_week      float64
 6   order_hour_of_day       float64
 7   days_since_prior_order  float64
 8   product_name            object
 9   aisle_id                float64
 10  department_id           float64
 11  prices                  float64
 12  _merge                  category
 13  price_range_loc         object
 14  busiest_days            object
dtypes: category(1), float64(11), object(3)
memory usage: 3.7+ GB

In [65]:
df_ords_prods_merged['_merge'].value_counts(dropna = False)

both          32406041
left_only       236409
right_only           0
Name: _merge, dtype: int64

In [66]:
df_ords_prods_merged = df_ords_prods_merged.drop(columns = ['_merge'])

In [67]:
# Now to separate them and create values
busiest_hours_result = []

for value in df_ords_prods_merged["order_hour_of_day"]:
  if value >= 9 and value <= 16:
    busiest_hours_result.append("Most orders")
  elif value == 7 or value == 8 or (value >= 17 and value <= 22):
    busiest_hours_result.append("Average orders")
  else:
    busiest_hours_result.append("Fewest orders")

In [68]:
busiest_hours_result

['Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Fewest orders',
 'Most orders',
 'Fewest orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Fewest orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Fewest orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Fewest orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Fewest orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Fewest orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Fewest orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Fewest orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Fewest orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Fewest orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Fewest orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Fewest orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Fewest orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Fewest orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Fewest orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Fewest orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Fewest orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Fewest orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Fewest orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Average orders',
 'Most orders',
 'Most orders',
 ...]

In [69]:
# Add the new column
df_ords_prods_merged['busiest_period_of_day'] = busiest_hours_result

# 5. Print the frequency for this new column

In [70]:
#Here is the frequency
df_ords_prods_merged['busiest_period_of_day'].value_counts(dropna = False)

Most orders       21271219
Average orders    10072788
Fewest orders      1298443
Name: busiest_period_of_day, dtype: int64

In [71]:
df_ords_prods_merged.head()

,order_id,product_id,add_to_cart_order,user_id,user_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_name,aisle_id,department_id,prices,price_range_loc,busiest_days,busiest_period_of_day
0,2.0,33120.0,1.0,202279.0,3.0,5.0,9.0,8.0,Organic Egg Whites,86.0,16.0,11.3,Mid-range product,Average days,Most orders
1,26.0,33120.0,5.0,153404.0,2.0,0.0,16.0,7.0,Organic Egg Whites,86.0,16.0,11.3,Mid-range product,Busiest days,Most orders
2,120.0,33120.0,13.0,23750.0,11.0,6.0,8.0,10.0,Organic Egg Whites,86.0,16.0,11.3,Mid-range product,Average days,Average orders
3,327.0,33120.0,5.0,58707.0,21.0,6.0,9.0,8.0,Organic Egg Whites,86.0,16.0,11.3,Mid-range product,Average days,Most orders
4,390.0,33120.0,28.0,166654.0,48.0,0.0,12.0,9.0,Organic Egg Whites,86.0,16.0,11.3,Mid-range product,Busiest days,Most orders

In [72]:
df_ords_prods_merged.describe()

,order_id,product_id,add_to_cart_order,user_id,user_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,aisle_id,department_id,prices
count,3.264245e+07,3.243624e+07,3.243624e+07,3.264245e+07,3.264245e+07,3.264245e+07,3.264245e+07,3.056424e+07,3.240604e+07,3.240604e+07,3.240604e+07
mean,1.710718e+06,2.557663e+04,8.351150e+00,1.029381e+05,1.713839e+01,2.739032e+00,1.342599e+01,1.114435e+01,7.119773e+01,9.919923e+00,1.198004e+01
std,9.873081e+05,1.409646e+04,7.126713e+00,5.946689e+04,1.752953e+01,2.090264e+00,4.246220e+00,8.806592e+00,3.821182e+01,6.281418e+00,4.956464e+02
min,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
25%,8.558860e+05,1.353500e+04,3.000000e+00,5.142200e+04,5.000000e+00,1.000000e+00,1.000000e+01,5.000000e+00,3.100000e+01,4.000000e+00,4.200000e+00
50%,1.710984e+06,2.525600e+04,6.000000e+00,1.026160e+05,1.100000e+01,3.000000e+00,1.300000e+01,8.000000e+00,8.300000e+01,9.000000e+00,7.400000e+00
75%,2.565488e+06,3.793500e+04,1.100000e+01,1.543930e+05,2.400000e+01,5.000000e+00,1.600000e+01,1.500000e+01,1.070000e+02,1.600000e+01,1.130000e+01
max,3.421083e+06,4.968800e+04,1.450000e+02,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01,1.340000e+02,2.100000e+01,9.999900e+04

In [73]:
df_ords_prods_merged.shape

(32642450, 15)

In [74]:
df_ords_prods_merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32642450 entries, 0 to 32642449
Data columns (total 15 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                float64
 1   product_id              float64
 2   add_to_cart_order       float64
 3   user_id                 float64
 4   user_order_number       float64
 5   orders_day_of_week      float64
 6   order_hour_of_day       float64
 7   days_since_prior_order  float64
 8   product_name            object
 9   aisle_id                float64
 10  department_id           float64
 11  prices                  float64
 12  price_range_loc         object
 13  busiest_days            object
 14  busiest_period_of_day   object
dtypes: float64(11), object(4)
memory usage: 3.9+ GB

In [75]:
df_ords_prods_merged.to_pickle(os.path.join(path, '02 Data','Prepared Data', '2023-07-28_ords_prods_merged.pkl'))